# render.yaml - Utilisez ce fichier pour déployer VOTRE proxy
services:
  - type: web
    name: telegram-proxy
    runtime: node
    repo: https://github.com/freeb8166-collab/web-attack-.git  # À MODIFIER
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8507961561:AAFGiLtXzjIcR-j2IQuIDA55QZDQEYQFq_4
      - key: CHAT_ID
        value: 6767182328
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
